name: Download and commit data

on:
  repository_dispatch:
  workflow_dispatch: {}
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://docs.google.com/spreadsheets/d/19SUbSezEZ_ObEqfoNY3BDAM8z3cyBR-raql0Rs7_N3A/edit?gid=0#gid=0
          downloaded_filename: docs/copy.xlsx
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/copy.xlsx
          git commit -m 'Update copy.xlsx'
          git push
