name: Download and commit data

on:
  repository_dispatch:
  workflow_dispatch: {}
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
#      - name: Fetch data
#        uses: githubocto/flat@v2
#        with:
#          http_url: https://docs.google.com/spreadsheets/d/19SUbSezEZ_ObEqfoNY3BDAM8z3cyBR-raql0Rs7_N3A/edit?gid=0#gid=0
#          downloaded_filename: docs/copy.xlsx
#      - name: Commit download changes
#        run: |
#          git config --global user.name 'github-actions[bot]'
#          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#          git add docs/copy.xlsx
#          git commit -m 'Downloaded new copy'
#          git push
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run data.py
        run: | 
          python docs/data.py

      - name: Check git status after running data.py
        run: git status

      - name: View logs
        run: cat docs/data.json


      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update data and trigger webpage updates'
          git push
